#### 1. Import NumPy as np

In [1]:
import numpy as np

#### 2. 創建一個包含10個零的陣列

In [ ]:
# CODE HERE


In [2]:
# DON'T WRITE HERE
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. 創建一個包含10個1的陣列

In [2]:
np.ones(10).reshape(5,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [3]:
# DON'T WRITE HERE
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. 產生10個5的陣列

In [4]:
# DON'T WRITE HERE
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. 創建一個包含從10到50的整數的陣列

In [5]:
# DON'T WRITE HERE
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. 要創建一個包含從10到50的所有偶數整數的陣列

In [6]:
# DON'T WRITE HERE
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. 要創建一個3x3矩陣，其中包含從0到8的值

In [7]:
# DON'T WRITE HERE
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. 要創建一個3x3的單位矩陣（identity matrix）

In [8]:
# DON'T WRITE HERE
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

####  要使用 NumPy 生成一個介於0和1之間的隨機數

In [9]:
# DON'T WRITE HERE
np.random.rand(1)

array([0.65248055])

#### 要使用 NumPy 生成一個包含25個從標準正態分布（平均值為0，標準差為1的正態分布）抽樣的隨機數陣列

In [10]:
# DON'T WRITE HERE
np.random.randn(25)

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 要創建一個包含從0到1之間20個等距點的陣列

In [12]:
# DON'T WRITE HERE
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

幫我產生以下的陣列

In [13]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 根據以下輸出完成功能

In [ ]:
# CODE HERE


In [14]:
# DON'T WRITE HERE
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 根據以下輸出完成功能

In [15]:
# DON'T WRITE HERE
mat[3,4]

20

#### 根據以下輸出完成功能

In [16]:
# DON'T WRITE HERE
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

#### 根據以下輸出完成功能

In [17]:
# DON'T WRITE HERE
mat[4,:]

array([21, 22, 23, 24, 25])

#### 根據以下輸出完成功能

In [18]:
# DON'T WRITE HERE
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## NumPy Operations

#### 18. 加總所有數據

In [19]:
# DON'T WRITE HERE
mat.sum()

325

#### 計算標準差

In [20]:
# DON'T WRITE HERE
mat.std()

7.211102550927978

#### 根據 columns 加總

In [21]:
# DON'T WRITE HERE
mat.sum(axis=0)

array([55, 60, 65, 70, 75])